/*
-- Query: SELECT * FROM Car_Center.SERVICES_OFFERED
LIMIT 0, 1000

-- Date: 2020-02-27 17:51
*/
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (1,'Sport_Car',NULL);
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (2,'SUV',NULL);
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (3,'Truck',NULL);
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (4,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (5,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (6,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (7,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (8,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (9,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (10,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (11,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (12,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (13,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (14,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (15,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (16,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (17,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (18,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (19,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (20,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (21,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (22,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (23,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (24,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (25,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (26,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (27,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (28,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (29,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (30,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (31,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (32,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (33,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (34,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (35,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (36,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (37,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (38,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (39,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (40,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (41,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (42,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (43,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (44,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (45,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (46,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (47,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (48,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (49,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (50,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (51,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (52,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (53,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (54,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (55,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (56,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (57,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (58,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (59,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (60,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (61,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (62,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (63,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (64,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (65,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (66,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (67,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (68,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (69,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (70,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (71,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (72,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (73,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (74,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (75,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (76,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (77,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (78,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (79,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (80,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (81,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (82,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (83,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (84,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (85,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (86,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (87,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (88,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (89,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (90,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (91,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (92,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (93,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (94,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (95,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (96,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (97,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (98,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (99,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (100,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (101,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (102,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (103,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (104,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (105,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (106,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (107,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (108,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (109,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (110,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (111,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (112,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (113,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (114,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (115,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (116,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (117,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (118,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (119,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (120,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (121,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (122,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (123,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (124,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (125,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (126,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (127,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (128,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (129,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (130,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (131,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (132,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (133,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (134,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (135,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (136,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (137,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (138,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (139,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (140,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (141,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (142,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (143,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (144,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (145,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (146,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (147,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (148,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (149,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (150,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (151,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (152,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (153,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (154,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (155,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (156,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (157,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (158,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (159,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (160,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (161,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (162,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (163,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (164,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (165,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (166,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (167,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (168,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (169,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (170,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (171,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (172,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (173,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (174,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (175,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (176,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (177,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (178,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (179,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (180,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (181,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (182,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (183,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (184,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (185,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (186,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (187,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (188,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (189,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (190,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (191,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (192,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (193,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (194,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (195,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (196,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (197,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (198,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (199,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (200,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (201,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (202,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (203,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (204,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (205,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (206,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (207,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (208,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (209,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (210,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (211,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (212,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (213,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (214,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (215,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (216,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (217,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (218,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (219,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (220,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (221,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (222,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (223,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (224,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (225,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (226,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (227,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (228,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (229,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (230,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (231,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (232,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (233,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (234,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (235,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (236,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (237,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (238,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (239,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (240,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (241,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (242,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (243,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (244,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (245,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (246,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (247,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (248,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (249,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (250,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (251,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (252,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (253,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (254,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (255,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (256,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (257,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (258,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (259,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (260,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (261,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (262,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (263,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (264,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (265,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (266,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (267,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (268,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (269,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (270,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (271,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (272,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (273,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (274,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (275,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (276,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (277,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (278,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (279,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (280,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (281,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (282,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (283,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (284,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (285,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (286,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (287,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (288,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (289,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (290,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (291,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (292,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (293,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (294,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (295,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (296,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (297,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (298,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (299,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (300,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (301,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (302,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (303,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (304,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (305,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (306,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (307,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (308,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (309,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (310,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (311,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (312,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (313,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (314,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (315,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (316,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (317,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (318,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (319,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (320,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (321,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (322,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (323,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (324,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (325,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (326,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (327,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (328,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (329,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (330,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (331,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (332,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (333,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (334,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (335,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (336,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (337,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (338,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (339,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (340,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (341,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (342,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (343,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (344,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (345,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (346,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (347,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (348,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (349,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (350,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (351,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (352,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (353,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (354,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (355,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (356,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (357,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (358,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (359,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (360,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (361,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (362,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (363,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (364,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (365,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (366,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (367,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (368,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (369,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (370,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (371,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (372,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (373,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (374,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (375,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (376,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (377,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (378,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (379,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (380,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (381,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (382,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (383,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (384,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (385,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (386,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (387,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (388,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (389,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (390,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (391,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (392,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (393,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (394,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (395,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (396,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (397,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (398,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (399,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (400,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (401,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (402,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (403,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (404,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (405,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (406,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (407,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (408,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (409,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (410,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (411,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (412,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (413,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (414,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (415,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (416,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (417,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (418,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (419,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (420,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (421,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (422,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (423,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (424,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (425,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (426,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (427,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (428,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (429,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (430,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (431,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (432,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (433,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (434,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (435,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (436,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (437,NULL,'MEXICO');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (438,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (439,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (440,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (441,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (442,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (443,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (444,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (445,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (446,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (447,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (448,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (449,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (450,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (451,NULL,'ENGLAND');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (452,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (453,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (454,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (455,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (456,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (457,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (458,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (459,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (460,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (461,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (462,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (463,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (464,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (465,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (466,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (467,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (468,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (469,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (470,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (471,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (472,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (473,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (474,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (475,NULL,'TURKEY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (476,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (477,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (478,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (479,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (480,NULL,'CANADA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (481,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (482,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (483,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (484,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (485,NULL,'ITALY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (486,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (487,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (488,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (489,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (490,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (491,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (492,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (493,NULL,'GERMANY');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (494,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (495,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (496,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (497,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (498,NULL,'TAIWAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (499,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (500,NULL,'FRANCE');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (501,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (502,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (503,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (504,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (505,NULL,'');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (506,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (507,NULL,'BELGIUM');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (508,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (509,NULL,'AUSTRIA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (510,NULL,'BRAZIL');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (511,NULL,'CHINA');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (512,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (513,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (514,NULL,'JAPAN');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (515,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (516,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (517,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (518,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (519,NULL,'UNITED STATES (USA)');
INSERT INTO `` (`service_offered`,`Sale`,`Country`) VALUES (520,NULL,'UNITED STATES (USA)');
